version: '3.8'

services:
  auth:
    build:
      context: ../
      dockerfile: build/auth/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network

  mainchat:
    build:
      context: ../
      dockerfile: build/mainchat/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - network

  postgres:
    image: postgres:15.3
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - ../db/data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    env_file:
      - ../configs/.env
    networks:
      - network

networks:
  network:
    driver: bridge